######################################################################
##
## Filename: ADC_CTRL.udo
## Created on: Sun Nov 06 12:04:48 GMT 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
