######################################################################
##
## Filename: SEQUENCER.udo
## Created on: Fri Nov 04 13:35:23 GMT 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
