######################################################################
##
## Filename: SPI_CORE.udo
## Created on: Thu Oct 06 10:12:42 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
