######################################################################
##
## Filename: SPI_DAC.udo
## Created on: Thu Oct 06 10:06:43 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
