######################################################################
##
## Filename: DIGIF.udo
## Created on: Mon Sep 26 13:45:13 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
