######################################################################
##
## Filename: DESERIAL_TB.udo
## Created on: Sun Sep 18 11:35:09 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
