######################################################################
##
## Filename: DESERIAL.udo
## Created on: Sat Sep 24 10:22:31 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
