######################################################################
##
## Filename: DIGIF.udo
## Created on: Sun Sep 18 13:21:43 BST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
